event-system/config/routes.rb
Rails.application.routes.draw do
  devise_for :user_auths
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "events#index"
end

event-system/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

event-system/app/models/event.rb
class Event < ApplicationRecord

  #validations 
  validates :name, presence: true, length: {maximum: 150}
  validates :date, presence: true

  #callbacks
  before_save :check_date

  #scopes
  scope :_30_days_range, -> {where("date <= ?" , (Date.today + 30))}
  scope :_filter_by_concierto, -> {where("name = 'concierto'")}
  
  
  private

  #checks that incoming date is equal or greater than today
  def check_date

    puts "esta es la fecha #{self.date}"
    puts "ESTO ES LA COMPARACIÓN #{self.date < Date.today}"
    if self.date < Date.today
      errors.add(:date, ":(Param) -> you can not save an old date, must be today or later")
      throw(:abort)
    end

  end


end

event-system/app/models/user_auth.rb
class UserAuth < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

event-system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

event-system/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user_auth!
  before_action :set_event, only: %i[ show edit update destroy ]

    #controllerScope = helpScope.new
  # GET /events or /events.json
  def index
    @eventsAll = Event.all 
    @events = Event._30_days_range
    #@events = Event._filter_by_concierto
    #events = controllerScope.showConcierto
    

  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :description)
    end
end

event-system/app/helpers/application_helper.rb
module ApplicationHelper
end

event-system/app/helpers/events_helper.rb
module EventsHelper
end

event-system/app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

</div>

event-system/app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

event-system/app/views/events/edit.html.erb
<% content_for :title, "Editing event" %>

<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

event-system/app/views/events/index.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<% content_for :title, "Events" %>

<h1>Events All</h1>

<div id="events">
  <% @eventsAll.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>

<h1>Show events from now to 30 days later</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>

event-system/app/views/events/new.html.erb
<% content_for :title, "New event" %>

<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

event-system/app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

event-system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Event System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color: green"><%= notice %></p>
    <p class="alert"><%= alert %></p>
         <%= button_to(
        "Log Out",
        destroy_user_auth_session_path,
        method: :delete,
        class: "btn btn-danger"
      )  %>
   
    <%= yield %>
  </body>
</html>